apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    k8.service: crawler
  name: crawler
spec:
  selector:
    matchLabels:
      k8.service: crawler
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8.service: crawler
    spec:
      containers:
      - env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: ARTIST
          value : Bastille 
        image: crawler:emotedet
        imagePullPolicy: IfNotPresent
        name: crawler
        resources: {}
        volumeMounts:
        - mountPath: /opt/tracks
          name: tracks
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /home/alawys/EmoteDet
        name: tracks
status: {}
