apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    k8.service: elastic
  name: elastic
spec:
  ports:
  - name: "9200"
    port: 9200
    targetPort: 9200
  selector:
    k8.service: elastic
status:
  loadBalancer: {}
