apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    k8.service: kafkaserver
  name: kafkaserver
spec:
  ports:
  - name: "9092"
    port: 9092
    targetPort: 9092
  - name: "9101"
    port: 9101
    targetPort: 9101
  - name: "8779"
    port: 8779
    targetPort: 8779
  selector:
    k8.service: kafkaserver
status:
  loadBalancer: {}
