apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    k8.service: logstash
  name: logstash
spec:
  ports:
  - name: "9600"
    port: 9600
    targetPort: 9600
  selector:
    k8.service: logstash
status:
  loadBalancer: {}
