apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    k8.service: spark
  name: spark
spec:
  ports:
  - name: "4040"
    port: 4040
    targetPort: 4040
  selector:
    k8.service: spark
status:
  loadBalancer: {}
