apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    k8.service: webui
  name: webui
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    k8.service: webui
status:
  loadBalancer: {}
